# Generated by Django 3.0.8 on 2020-07-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=True, max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=32)),
                ('confirmpassword', models.CharField(default=True, max_length=32)),
            ],
        ),
    ]
