# Generated by Django 3.0.8 on 2020-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fullname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
    ]
