# Generated by Django 3.0.8 on 2020-07-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20200718_1030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table=None,
        ),
    ]
