# Generated by Django 3.0.8 on 2020-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20200718_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
