# Generated by Django 3.0.8 on 2020-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20200718_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='media_cdn/profile_pics'),
        ),
    ]
